---
- name: ensure xmonad and tools are installed
  yum: name={{ item }} state=latest
  sudo: yes
  tags: packages
  with_items:
    - xmonad
    - xmobar
    - xautolock
    - xlockmore
    - parcellite
    - workrave
    - pidgin
    - hamster-time-tracker
    - xfce4-terminal

- name: clone xmonad git repository
  git:
    repo: "{{ github_repository }}/xmonad-conf.git"
    dest: "{{ configs_path }}/xmonad-conf"
    version: "{{ xmonadconf_branch }}"
    accept_hostkey: yes

- name: Remove (old) XMonad configuration
  command: make uninstall
  args:
    chdir: "{{ configs_path }}/xmonad-conf"
  ignore_errors: true

- name: Install XMonad configuration
  command: make install
  args:
    chdir: "{{ configs_path }}/xmonad-conf"

- name: Configure Xresources
  template:
    src: Xresources.j2
    dest: "{{ user_home }}/.Xresources"

- name: Configure xmobar
  tags: xmobar
  template:
    src: xmobarrc.j2
    dest: "{{ user_home }}/.xmobarrc"

- name: Verify xmobar configuration
  tags: xmobar
  command: xmobar --help
  failed_when: result.stderr
  register: result
