---
- name: ensure xmonad and tools are installed
  yum: name={{ item }} state=latest
  sudo: yes
  with_items:
    - xmonad
    - xmobar
    - xautolock
    - xlockmore
    - parcellite
    - workrave
    - pidgin
    - hamster-time-tracker
    - terminator

- name: clone xmonad git repository
  git:
    repo: "{{ github_repository }}/xmonad-conf.git"
    dest: "{{ configs_path }}/xmonad-conf"
    accept_hostkey: yes

- name: Remove (old) XMonad configuration
  command: make uninstall
  args:
    chdir: "{{ configs_path }}/xmonad-conf"
  ignore_errors: true

- name: Install XMonad configuration
  command: make install
  args:
    chdir: "{{ configs_path }}/xmonad-conf"
