---
- name: ensure xmonad and tools are installed
  dnf: name={{ item }} state=latest
  become: yes
  tags: packages
  with_items:
    - xmonad
    - xmobar
    - xautolock
    - xlockmore
    - parcellite
    - workrave
    - pidgin
    - hamster-time-tracker
    - xfce4-terminal

- name: ensure local xmonad directory
  file:
    state: directory
    path: "{{ user_home }}/.xmonad"

- name: deploy startup hook
  template:
    src: startup-hook.j2
    dest: "{{ user_home }}/.xmonad/startup-hook"
    mode: 0755

- name: Configure Xresources
  template:
    src: Xresources.j2
    dest: "{{ user_home }}/.Xresources"

- name: Configure xsession
  copy:
    src: xsession
    dest: "{{ user_home }}/.xsession"
    mode: 0755

- name: Configure Xmonad
  template:
    src: xmonad.hs.j2
    dest: "{{ user_home }}/.xmonad/xmonad.hs"

- name: Configure xmobar
  tags: xmobar
  template:
    src: xmobarrc.j2
    dest: "{{ user_home }}/.xmobarrc"

- name: Verify xmobar configuration
  tags: xmobar
  command: xmobar --help
  failed_when: result.stderr
  register: result
