---
- name: Full deployment
  hosts: local
  connection: local
  roles:
    - { role: common, tags: [common] }
    - { role: shell/zsh, tags: [shell, zsh] }
    - { role: shell/apps, tags: [shell, apps] }
    - { role: gui/wm/xmonad, dpi: 158, tags: [gui, xmonad] }
    - { role: gui/fonts, tags: [gui, fonts] }
    - { role: gui/apps, tags: [apps] }
    - { role: vim, tags: vim }
    - { role: emacs, tags: emacs }
    - { role: devel/languages/haskell, tags: [haskell, languages] }
    - { role: devel/languages/python, tags: [python, languages] }
    - { role: mail/mutt, tags: [mail, mutt] }
    - { role: mail/getmail, tags: [mail, mda] }
    - { role: tmux, tags: [terminal, tmux] }
    - { role: auth, tags: [sssd, auth] }
