- name: Full deployment
  hosts: local
  connection: local
  roles:
  - { role: common, tags: [common] }
  - { role: shell/zsh, tags: [shell, zsh] }
  - { role: shell/apps, tags: [shell, apps] }
  - { role: gui/wm/xmonad, tags: [gui, xmonad] }
  - { role: gui/fonts, tags: [gui, fonts] }
  - { role: gui/apps, tags: [apps] }
  - { role: vim, tags: vim }
  - { role: emacs, tags: emacs }
  - { role: devel/apps, tags: [devel, apps, languages] }
  - { role: devel/languages/haskell, tags: [devel, haskell, languages] }
  - { role: devel/languages/python, tags: [devel, python, languages] }
  - { role: devel/docker, tags: docker }
  - { role: ddns, tags: [services, ddns] }
  - { role: mail/mutt, tags: [mail, mutt] }
  - { role: mail/getmail, tags: [mail, mda] }
  - { role: auth, tags: [sssd, auth] }
