---
- name: ensure virtualenv is installed
  become: true
  tags: packages
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - python-virtualenv
    - python-virtualenvwrapper

- name: Create virtualenv
  command: virtualenv {{ user_home }}/tools/python{{ ansible_python_version }} 
  register: virtualenv_output

- debug: var=virtualenv_output
