---
- name: get stack repository
  become: yes
  command: dnf copr enable -y petersen/stack
  when: ansible_distribution == "Fedora"

- name: install packages
  become: yes
  tags: packages
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
    - stack
    - zlib-devel
    - happy
