---
- name: ensure offlineimap is installed
  sudo: yes
  dnf:
    name: "offlineimap"
    state: latest

- name: install new offlineimap conf
  template:
    src: offlineimaprc.j2
    dest: "{{ user_home }}/.offlineimaprc"
    mode: 0600

- name: write systemd service
  sudo: yes
  copy:
    src: offlineimap@.service
    dest: "/etc/systemd/system/offlineimap@.service"
    mode: 644

- name: restart systemd daemon
  sudo: yes
  command: systemctl daemon-reload

- name: enable offlinemap service
  sudo: yes
  service:
    name: offlineimap@{{ ansible_user_id }}.service
    enabled: yes
    state: started
