---
- name: ensure offlineimap is installed
  sudo: yes
  dnf:
    name: "offlineimap"
    state: latest

- name: install new offlineimap conf
  copy:
    src: offlineimaprc
    dest: "{{ user_home }}/.offlineimaprc"
    backup: yes
  register: offlineimap_config

- debug:
    var: offlineimap_config