---
- name: ensure offlineimap is installed
  sudo: yes
  dnf:
    name: "offlineimap"
    state: latest

- name: install new offlineimap conf
  template:
    src: offlineimaprc.j2
    dest: "{{ user_home }}/.offlineimaprc"
    mode: 0600

- name: user systemd dir exists
  file:
    state: directory
    path: "{{ user_home }}/.config/systemd/user"

- name: ensure service is defined
  copy:
    src: offlineimap.service
    dest: "{{ user_home }}/.config/systemd/user/offlineimap.service"
    mode: 0644

- name: ensure timer is defined
  copy:
    src: offlineimap.timer
    dest: "{{ user_home }}/.config/systemd/user/offlineimap.timer"
    mode: 0644

- name: enable offlinemap timer
  systemd:
    name: offlineimap.timer
    enabled: yes
    state: started
    user: yes
    daemon_reload: yes
