---
- name: ensure emacs is installed
  dnf: name=emacs state=latest
  sudo: yes

- name: clone my emacs setup
  git:
    repo: "{{ github_repository }}/emacsrc.git"
    dest: "{{ configs_path }}/emacsrc"
    accept_hostkey: yes

- name: remove old emacs installation
  command: make uninstall
  args:
    chdir: "{{ configs_path }}/emacsrc"
  ignore_errors: true

- name: additional development tools for plugins
  tags: packages
  dnf:
    name: "{{ item }}"
    state: latest
  sudo: yes
  with_items:
    - ctags
    - hlint
    - python-flake8
    - nodejs-tern
    - the_silver_searcher
    - ack
