---
- name: ensure docker is installed
  become: yes
  tags: packages
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - docker
    - docker-compose

- name: make sure docker is started on book
  become: yes
  service:
    name: docker
    state: started
    enabled: yes
