---
- name: ensure docker is installed
  become: yes
  tags: packages
  dnf:
    name: docker
    state: present

- name: make sure docker is started on book
  become: yes
  service:
    name: docker
    state: started
    enabled: yes
