---
- name: ensure xmonad and tools are installed
  yum: name={{ item }} state=latest
  sudo: yes
  with_items:
    - xmonad
    - xmobar
    - xautolock
    - xlockmore
    - parcellite
    - workrave
    - pidgin
    - hamster-time-tracker

- name: clone xmonad git repository
  git:
    repo: "{{ github_repository }}/xmonad-conf.git"
    dest: "{{ configs_path }}/xmonad-conf"
    accept_hostkey: yes
