---
- name: ensure xmonad and tools are installed
  yum: name={{ item }} state=latest
  sudo: yes
  with_items:
    - xmonad
    - xmobar
    - xautolock
    - parcellite
    - workrave
    - pidgin
    - hamster-time-tracker

- name: clone xmonad git repository
  git:
    repo: "{{ zsh_git_repository }}/xmonad-conf.git"
    dest: "{{ user_home }}/tools/xmonad-conf"
    accept_hostkey: yes
