- name: Full deployment
  hosts: local
  connection: local
  roles:
    - { role: common, tags: [common] }
    - { role: shell, tags: [shell, zsh] }
    - { role: gui/wm/xmonad, tags: [gui, xmonad] }
    - { role: gui/fonts, tags: [gui, fonts] }
    - { role: gui/apps, tags: [apps] }
    - { role: vim, tags: vim }
    - { role: emacs, tags: emacs }
    - { role: devel/languages/haskell, tags: [haskell, languages] }
    - { role: devel/languages/python, tags: [python, languages] }
    - { role: mail/mutt, tags: mail }
    - { role: mail/offlineimap, tags: [mail, mda] }
