---
- name: user systemd dir exists
  file:
    state: directory
    path: "{{ user_home }}/.config/systemd/user"

- name: ensure service is defined
  template:
    src: ddns.service.j2
    dest: "{{ user_home }}/.config/systemd/user/ddns.service"
    mode: 0644
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"

- name: ensure ddns timer is defined
  copy:
    src: ddns.timer
    dest: "{{ user_home }}/.config/systemd/user/ddns.timer"
    mode: 0644

- name: enable ddns timer
  systemd:
    name: ddns.timer
    enabled: yes
    state: started
    user: yes
    daemon_reload: yes
