---
- name: ensure service is defined
  become: yes
  template:
    src: ddns.service.j2
    dest: /etc/systemd/system/ddns.service
    mode: 0644
    owner: root
    group: root

- name: ensure ddns timer is defined
  become: yes
  copy:
    src: ddns.timer
    dest: /etc/systemd/system/ddns.timer
    mode: 0644

- name: enable ddns timer
  become: yes
  systemd:
    name: ddns.timer
    enabled: yes
    state: started
    daemon_reload: yes
