---
- name: ensure vim installed
  dnf: name=vim state=latest
  become: yes

- name: clone my vim setup
  git:
    repo: "{{ github_repository }}/vimrc.git"
    dest: "{{ configs_path }}/vimrc"
    accept_hostkey: yes

- name: additional development tools for plugins
  dnf: name=ctags state=latest
  become: yes
