---
- name: Install runtime dependencies
  become: yes
  tags: lbdb
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - lbdb
    - a2ps
    - recode
    - gnupg
    - gpgme-devel
    - elinks
    - odt2txt
    - urlview
    - t-prot

- name: ensure ldap directory
  tags: lbdb
  file:
    path: "{{ user_home }}/.lbdb"
    state: directory
    mode: 0700

- name: configure lbdb
  tags: lbdb
  template:
    src: lbdbrc.j2
    dest: "{{ user_home }}/.lbdb/rc"
    mode: 0600
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"

- name: configure lbdb LDAP
  tags: lbdb
  template:
    src: ldap.rc.j2
    dest: "{{ user_home }}/.lbdb/ldap.rc" 
    mode: 0600
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"

- name: Solarized for mutt
  git:
    repo: https://github.com/altercation/mutt-colors-solarized.git
    dest: "{{ user_home }}/works/mutt-colors-solarized"

- name: Install development tools
  become: yes
  dnf:
    name: "@Development Tools"
    state: present 

- name: Install compile dependencies
  become: yes
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
    - autoconf
    - automake
    - gettext-devel
    - ncurses-devel
    - notmuch-devel
    - openssl-devel
    - tokyocabinet-devel
    - cyrus-sasl-devel

- name: Clone mutt repository
  git:
    repo: https://github.com/neomutt/neomutt
    dest: "{{ project_home }}"
    version: master

- name: Install mutt
  command: "{{ item }}"
  args:
    chdir: "{{ project_home }}"
  with_items:
    - "git clean -xdf"
    - ./prepare
    - ./configure --enable-notmuch --enable-gpgme --enable-imap --with-sasl --with-ssl --enable-smtp --enable-hcache --prefix={{ prefix }} 
    - make

- name: install mutt
  become: yes
  command: make install
  args:
    chdir: "{{ project_home }}"

- name: fix up ownership in mutt
  become: yes
  command: "sudo chown -R {{ ansible_user_id }}.{{ ansible_user_id }} {{ prefix }}"

- name: ensure users local exists
  file:
    path: "{{ user_home }}/.local/bin"
    state: directory
    mode: 0755

- name: create a local link to mutt
  file:
    src: "{{ prefix }}/bin/neomutt"
    dest: "{{ user_home }}/.local/bin/mutt"
    state: link
