---
- name: ensure delivery packages are installed
  sudo: yes
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
  - getmail
  - maildrop

- name: install notmuch compile deps
  sudo: yes
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
    - libtool
    - notmuch-devel
    - glib2-devel

- name: clone notmuch repository for notmuch-deliver
  git:
    repo: https://github.com/sbinet/notmuch.git
    dest: "{{ project_base_home }}"

- name: Clean repository
  command: git clean -xdf
  args:
    chdir: "{{ project_base_home }}"

- name: install notmuch-deliver
  command: "{{ item }}"
  args:
    chdir: "{{ project_home }}"
  with_items:
    - "./autogen.sh"
    - "./configure --prefix={{ user_home }}/.local"
    - make
    - make install

- name: install mailfilter
  copy:
    src: mailfilter
    dest: "{{ user_home }}/.mailfilter"
    mode: 0600
    
- name: prepare maildrop test
  copy:
    src: testmail
    dest: /tmp/testmail

- name: Test deliver mail through maildrop
  shell: cat /tmp/testmail | maildrop -V9 -d
  register: output

- debug:
    var: output

- name: remove testmail
  file:
    state: absent
    path: /tmp/testmail
  
- name: Create getmail default config folder
  file:
    state: directory
    path: "{{ user_home }}/.getmail"

- name: Configure getmail
  template:
    src: getmail.j2
    dest: "{{ user_home }}/.getmail/getmailrc" 
    mode: 0600
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"

- name: Check getmail config
  command: getmail --dump
  failed_when: result.rc > 1
  register: result

- name: user systemd dir exists
  file:
    state: directory
    path: "{{ user_home }}/.config/systemd/user"

- name: ensure service is defined
  copy:
    src: getmail.service
    dest: "{{ user_home }}/.config/systemd/user/getmail.service"
    mode: 0644

- name: enable getmail service
  systemd:
    name: getmail.service
    enabled: yes
    state: started
    user: yes
    daemon_reload: yes
